# Generated by Django 5.0.5 on 2024-05-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_doctor_department_alter_doctor_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
